import type { ProjectileDefinition, ProjectileDefinitionId } from './ProjectileDefinition';

export const projectileDefinitions: Readonly<Record<ProjectileDefinitionId, ProjectileDefinition>> =
  Object.freeze({
    basicShell: Object.freeze({
      id: 'basicShell',
      name: 'Basic Shell',
      massKg: 5,
      radiusMeters: 0.12,
      gravityScale: 1,
      windInfluence: 1,
      dragCoefficient: 1,
      maxLifetimeSeconds: 20,
      impactDefinitionId: 'basicImpact',
      ricochet: Object.freeze({
        enabled: true,
        minRicochetAngleDeg: 70,
        minSpeedMetersPerSecond: 10,
        energyRetention: 0.55,
        maxRicochets: 1,
      }),
      penetration: Object.freeze({
        enabled: false,
        penetrationPower: 1,
        penetrationRadiusMeters: 0.16,
        maxPenetrationDistanceMeters: 2,
        minimumExitEnergyJ: 20,
      }),
    }),
    mortarShell: Object.freeze({
      id: 'mortarShell',
      name: 'Mortar Shell',
      massKg: 9,
      radiusMeters: 0.18,
      gravityScale: 1,
      windInfluence: 1,
      dragCoefficient: 1,
      maxLifetimeSeconds: 20,
      impactDefinitionId: 'mortarImpact',
      ricochet: Object.freeze({
        enabled: false,
        minRicochetAngleDeg: 80,
        minSpeedMetersPerSecond: 12,
        energyRetention: 0.35,
        maxRicochets: 0,
      }),
      penetration: Object.freeze({
        enabled: false,
        penetrationPower: 0.4,
        penetrationRadiusMeters: 0.22,
        maxPenetrationDistanceMeters: 0.8,
        minimumExitEnergyJ: 50,
      }),
    }),
    penetratorShell: Object.freeze({
      id: 'penetratorShell',
      name: 'Heavy Penetrator Shell',
      massKg: 14,
      radiusMeters: 0.16,
      gravityScale: 1,
      windInfluence: 1,
      dragCoefficient: 1,
      maxLifetimeSeconds: 20,
      impactDefinitionId: 'penetratorImpact',
      ricochet: Object.freeze({
        enabled: true,
        minRicochetAngleDeg: 60,
        minSpeedMetersPerSecond: 10,
        energyRetention: 0.65,
        maxRicochets: 2,
      }),
      penetration: Object.freeze({
        enabled: true,
        penetrationPower: 4,
        penetrationRadiusMeters: 0.18,
        maxPenetrationDistanceMeters: 24,
        minimumExitEnergyJ: 50,
      }),
    }),
  });
